name: Hello world

on:
  push:
    branches: [ master ]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      - name: say-helloo!
        run: |
          echo Hello, there!!
