name: Hello world

on:
  push:
    branches: [ master ]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: say-helloo!
        run: |
          echo Hello, there!!
          
      - name: say-date!
        run: echo date
        
      - name: run ls -l
        run: ls -l
